version: '3'

services:
   my-db-srvr:
      image: mysql:5.7
      volumes:
         - mysql_storage:/var/lib/mysql
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: docker
         MYSQL_USER: user
         MYSQL_PASSWORD: docker
         MYSQL_DATABASE: mydb

   my-web-srvr:
      image: wordpress:5.1.1-php7.3-apache
      restart: always
      depends_on:
         - my-db-srvr
      ports:
         - 8081:80
      environment:
         WORDPRESS_DB_HOST: my-db-srvr
         WORDPRESS_DB_USER: user
         WORDPRESS_DB_PASSWORD: docker
         WORDPRESS_DB_NAME: mydb
      volumes:
         - wp_storage:/var/www/html

volumes:
   wp_storage:
   mysql_storage:
